from __future__ import annotations

from dataclasses import dataclass

from app.modules.imports.application.contracts import ImportTemplate


@dataclass(slots=True, frozen=True)
class TemplateDefinition:
    template: ImportTemplate
    required_headers: tuple[str, ...]


TEMPLATES: dict[ImportTemplate, TemplateDefinition] = {
    "customers": TemplateDefinition(
        template="customers",
        required_headers=(
            "source_record_id",
            "legal_name",
            "trade_name",
            "document_number",
            "status",
            "billing_street",
            "billing_number",
            "billing_district",
            "billing_city",
            "billing_state",
            "billing_country",
            "billing_postal_code",
            "contact_email",
            "contact_phone",
            "external_id",
        ),
    ),
    "products": TemplateDefinition(
        template="products",
        required_headers=(
            "source_record_id",
            "sku",
            "name",
            "category",
            "unit_of_measure",
            "status",
            "default_cost",
            "default_price",
            "tax_profile_ref",
            "external_id",
        ),
    ),
    "sales": TemplateDefinition(
        template="sales",
        required_headers=(
            "company_id",
            "period_ref",
            "source_record_id",
            "transaction_date",
            "invoice_id",
            "invoice_line_id",
            "product_external_id",
            "customer_external_id",
            "gross_revenue",
            "tax_amount",
            "discount_amount",
            "return_amount",
            "net_revenue",
            "quantity_sold",
            "cogs_amount",
        ),
    ),
    "cashflow": TemplateDefinition(
        template="cashflow",
        required_headers=(
            "company_id",
            "period_ref",
            "source_record_id",
            "transaction_date",
            "cash_flow_type",
            "account_type",
            "cash_in_amount",
            "cash_out_amount",
            "operating_cash_flow_amount",
            "description",
        ),
    ),
    "financial": TemplateDefinition(
        template="financial",
        required_headers=(
            "company_id",
            "period_ref",
            "source_record_id",
            "transaction_date",
            "cash_flow_type",
            "account_type",
            "cash_in_amount",
            "cash_out_amount",
            "operating_cash_flow_amount",
            "description",
        ),
    ),
    "balance_sheet": TemplateDefinition(
        template="balance_sheet",
        required_headers=(
            "company_id",
            "period_ref",
            "reference_date",
            "source_record_id",
            "current_assets",
            "non_current_assets",
            "cash_and_equivalents",
            "inventory",
            "accounts_receivable",
            "other_current_assets",
            "current_liabilities",
            "non_current_liabilities",
            "accounts_payable",
            "total_assets",
            "total_liabilities",
            "equity",
        ),
    ),
    "income_statement": TemplateDefinition(
        template="income_statement",
        required_headers=(
            "company_id",
            "period_ref",
            "source_record_id",
            "gross_revenue",
            "net_revenue",
            "cogs",
            "gross_profit",
            "operating_expenses",
            "ebit",
            "depreciation",
            "amortization",
            "ebitda",
            "financial_income",
            "financial_expense",
            "income_before_tax",
            "income_tax",
            "net_income",
            "nopat",
        ),
    ),
    "accounts_receivable": TemplateDefinition(
        template="accounts_receivable",
        required_headers=(
            "company_id",
            "period_ref",
            "source_record_id",
            "customer_id",
            "invoice_number",
            "issue_date",
            "due_date",
            "payment_date",
            "amount",
            "received_amount",
            "outstanding_amount",
            "status",
            "aging_days",
        ),
    ),
    "accounts_payable": TemplateDefinition(
        template="accounts_payable",
        required_headers=(
            "company_id",
            "period_ref",
            "source_record_id",
            "supplier_id",
            "invoice_number",
            "issue_date",
            "due_date",
            "payment_date",
            "amount",
            "paid_amount",
            "outstanding_amount",
            "status",
            "aging_days",
        ),
    ),
    "inventory": TemplateDefinition(
        template="inventory",
        required_headers=(
            "company_id",
            "period_ref",
            "source_record_id",
            "product_id",
            "warehouse_id",
            "snapshot_date",
            "opening_quantity",
            "closing_quantity",
            "average_quantity",
            "average_cost",
            "inventory_value",
            "stock_turnover",
            "days_in_inventory",
        ),
    ),
    "hr": TemplateDefinition(
        template="hr",
        required_headers=(
            "company_id",
            "period_ref",
            "source_record_id",
            "employee_count",
            "active_employee_count",
            "terminated_employee_count",
            "payroll_amount",
            "average_salary",
            "hours_worked",
        ),
    ),
}


def get_template(template: ImportTemplate) -> TemplateDefinition:
    return TEMPLATES[template]
